/-
Copyright (c) 2026. All rights reserved.
Author: Julián Calderón Almendros
License: MIT
-/

-- Root module: auto-generated by gen-root.bash
-- Run 'bash gen-root.bash' after adding or removing modules.

import AczelSetTheory.CSets
