/-
Copyright (c) 2026. All rights reserved.
Author: Julián Calderón Almendros
License: MIT
-/

-- Root module: auto-generated by gen-root.bash
-- Uses barrel imports for subdirectories (see AI-GUIDE.md §23, §30–33).
-- Run 'bash gen-root.bash' after adding or removing modules.

import AczelSetTheory.PList
import AczelSetTheory.Axioms
import AczelSetTheory.CList
import AczelSetTheory.Operations
import AczelSetTheory.HFSets
import AczelSetTheory.HFList
import AczelSetTheory.HFListOps
import AczelSetTheory.Notation
import AczelSetTheory.VN
import AczelSetTheory.Algebra
import AczelSetTheory.Integers
import AczelSetTheory.Topology
import AczelSetTheory.Combinatorics
